---

- name: configure networking for RPM based general purpose instance
  hosts: 192.168.169.90
  user: root
  sudo: no
  gather_facts: no

  tasks:

    - name: update the boot protocol (not dhcp)
      lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                  regexp=^BOOTPROTO=
                  line=BOOTPROTO=none
                  state=present

    - name: use the network configuration on boot
      lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                  regexp=^ONBOOT=
                  line=ONBOOT=yes
                  state=present

    - name: update the subnet mask
      lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                  regexp=^NETMASK=
                  line=NETMASK=${netmask}
                  state=present

    - name: update the gateway
      lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                  regexp=^GATEWAY=
                  line=GATEWAY=${gateway}
                  state=present

    - name: update dns
      lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                  regexp=^DNS1=
                  line=DNS1=${gateway}
                  state=present

    - name: remind that the Ansible may time out
      debug: msg="May time out after changing the IP or restarting the network"

    - name: update the ip address
      lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                  regexp=^IPADDR=
                  line=IPADDR=${newip}
                  state=present

    - name: restart the network
      service: name=network state=restarted
