---

# TODO: symlink prezto as well
# TODO: make this work with ec2 as well -- need a dev environment accessible from the cloud. will need an option to install the desktop environment via yum and vnc/whatever. use conditionals to check if this dev instance is on premise or in the cloud.
# TODO: load passwords more securely (eg. encrypted in files)
# TODO: switch over orch stuff to dev instance (need to commit it to my github (private config?))
# TODO: install/configure google drive
# TODO: fix powerline (fonts, symbols, etc)
# TODO: set up reference files and anything else required
# TODO: figure out how to share working files (eg. Projects dir) between dev environments. need to make sure they're synced across (maybe using rsync back to my mac?). alternatively, consider dropbox situation.
# TODO: consider universal password managers
# TODO: transfer profile vars
# TODO: split out aws tools

# uncomment the wheel group line (TODO: no way to automate this?)
# %wheel    ALL=(ALL)    NOPASSWD:ALL

- name: configure RPM based dev instances
  hosts: ${hosts}
  gather_facts: no

  tasks:

    - name: set the shell for ${sudo_user}
      user: name=${sudo_user}
            groups=wheel
            state=present
            shell=${shell}

    - name: transfer profile
      copy: src=files/zprofile
            dest=/home/${sudo_user}/.zprofile

    - name: add google chrome repository
      copy: src=files/google-chrome.repo
            dest=/etc/yum.repos.d/google-chrome.repo
      when_set: ${install_gui_tools}

    - name: disable password login
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp=^PasswordAuthentication
                  line="PasswordAuthentication no"
                  state=present

    - name: disable root login
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp=^PermitRootLogin
                  line="PermitRootLogin no"
                  state=present

    - name: add google chrome repository
      copy: src=files/google-chrome.repo
            dest=/etc/yum.repos.d/google-chrome.repo
      when_set: ${install_gui_tools}

    - name: install dev tools
      yum: name=${item} state=latest
      with_items:
        - python3
        - java-1.7.0-openjdk-devel
        - tomcat6
        - jetty
        - nginx
        - ldapvi
        - varnish
        - nmap
        - git
        - svn
        - zsh
        - google-chrome-stable
        - ansible
        - ansible-fireball
        - aws-tools
        - euca2ools
        - wireshark
        - tcpdump
        - fortune-mod
        - sl

    - name: install pip
      easy_install: name=pip

    - name: create projects dir
      file: path=/home/${sudo_user}/Documents/projects
            owner=${sudo_user}
            group=${sudo_user}
            state=directory

    - name: create conf dir
      file: path=/home/${sudo_user}/conf/dotfiles
            state=directory

    - name: create dotfiles dir
      file: path=/home/${sudo_user}/conf/dotfiles
            state=directory

    - name: create dotvim dir
      file: path=/home/${sudo_user}/conf/dotvim
            state=directory

    - name: configure global git properties
      template: src=templates/gitconfig
                dest=/home/${sudo_user}/.gitconfig

    - name: checkout dotfiles repository
      git: repo=https://github.com/mbadran/dotfiles.git
           dest=/home/${sudo_user}/conf/dotfiles

    # # FIXME
    # - name: create local email config
    #   ini_file: dest=/home/${sudo_user}/conf/dotfiles/.git/config
    #              section=user
    #              option=email
    #              value=${github_email}

    - name: checkout dotvim repository
      git: repo=https://github.com/mbadran/dotvim.git
           dest=/home/${sudo_user}/conf/dotvim

    # # FIXME
    # - name: create local email config
    #   ini_file: dest=/home/${sudo_user}/conf/dotvim/.git/config
    #              section=user
    #              option=email
    #              value=${github_email}

    - name: checkout prezto repository
      git: repo=https://github.com/mbadran/prezto.git
           dest=/home/${sudo_user}/conf/prezto

    # # FIXME
    # - name: create local email config
    #   ini_file: dest=/home/${sudo_user}/conf/prezto/.git/config
    #              section=user
    #              option=email
    #              value=${github_email}

    - name: checkout vundle repository
      git: repo=https://github.com/gmarik/vundle
           dest=/home/${sudo_user}/.vim/bundle/vundle

    - name: symlink vim dotfiles
      file: src=/home/${sudo_user}/conf/dotvim
            dest=/home/${sudo_user}/.vim
            state=link

    - name: symlink vimrc
      file: src=/home/${sudo_user}/conf/dotvim/vimrc
            dest=/home/${sudo_user}/.vimrc
            state=link

    - name: symlink gvimrc
      file: src=/home/${sudo_user}/conf/dotvim/gvimrc
            dest=/home/${sudo_user}/.gvimrc
            state=link

    - name: symlink tmux conf
      file: src=/home/${sudo_user}/conf/dotfiles/tmux.conf
            dest=/home/${sudo_user}/.tmux.conf
            state=link

    - name: install powerline for vim
      pip: name=https://github.com/Lokaltog/powerline/tarball/develop
           state=present

    - include: tasks/nhccn.yml
