---

- name: transfer gateway package
  copy: src=roles/mbadran.caapigateway/files/{{ gateway_package }}
             dest=/tmp

- name: install gateway package
  yum: name=/tmp/{{ gateway_package }}
       state=present

- name: show gateway setup command
  debug: msg="run /opt/SecureSpan/Gateway/runtime/bin/setup.sh"
