---

# TODO: test on AWS
# TODO: test clustering again
# TODO: test taking down a (theoretically) unhealthy server and rebuilding it and adding it to the cluster. for maximum effect, this should be the first server in the node. and make changes after bringing it down to see if it will replicate when you bring it back up.
# TODO: test with a third server (will need to reboot for that). this could have a console attached, as opposed to the first 2 in a user facing cluster.
#
# TODO: review these:
# http://feed.askmaclean.com/archives/spin-up-the-forgerock-open-identity-stack-ois-using-ansible-and-vagrant.html
# https://github.com/wstrange/frstack
# http://blog.warrenstrange.com
# http://wiki.opencsi.com/public/bin/view/OpenAM/SilentInstallation
# http://blog.profiq.cz/2012/01/19/automated-installation-and-configuration-of-openam/
# https://github.com/ConductAS/puppet-openam
# https://github.com/dgardnersf/puppet-openam

# assumptions: openam 11.0.0. staging environment. locally available build
# files. embedded opendj data/config store. no external user stores or further
# config. rhel based systems. tomcat6. 1,024mb jvm.

# the following build vars are required:
#
# - hostname
# - cookie_domain
# - deployment_uri
# - root_suffix
# - admin_password
# - policy_agent_password
# - config_store_password

# the following build vars are optional and ignored by default:
#
# - install_headless (any value to enable)
# - install_tools (any value to enable)
# - join_site (any value to enable)
#     - encryption_key
#     - lb_site_name
#     - lb_primary_url
#     - existing_server_hostname
#     - existing_server_id
# - java_opts (defaults to "-Xmx1024m -XX:MaxPermSize=256m")
# - container_ssl (any value to enable)
#     - container_storepass (keystore storepass and keypass (they must be identical))

- name: fail if required build vars are unset
  fail: msg="please set all required build variables"
  with_items:
    - "{{ hostname }}"
    - "{{ cookie_domain }}"
    - "{{ deployment_uri }}"
    - "{{ root_suffix }}"
    - "{{ admin_password }}"
    - "{{ policy_agent_password }}"
    - "{{ config_store_password }}"
  # when: item is not defined
  # when: not item
  # when: item == None
  # FIXME: this is a hack, i would expect 'is not defined' to work. maybe a bug to do with loops?
  when: item.startswith("{{")

- name: fail if container_storepass is defined while container_ssl is undefined
  fail: msg="please provide container_ssl"
  when: container_storepass is defined and container_ssl is not defined

- name: fail if join_site is defined while other site/cluster variables are undefined
  fail: msg="please provide all site/cluster related variables"
  when: join_site is defined and (encryption_key is not defined or lb_site_name is not defined or lb_primary_url is not defined or existing_server_id is not defined or existing_server_hostname is not defined)

- include: system.yml
- include: install.yml
- include: initialise.yml

- name: show openam url
  debug: msg="success! log in to openam at {{ server_name }}"
