---

# TODO: compare this playbook with the hda one.

# this playbook verifies the openam installation and does some default configuration

# any further config or customisation should go in specific playbooks for your
# own setup (ie. one or more configuration.yml files).

- hosts: $hosts
  gather_facts: no

  vars_files:
    - ../vars/main.yml

  vars:
    - server_name: "{{ server_url }}/{{ deployment_uri }}"
    - password_file: /tmp/password.txt
    - admin_creds: --adminid amadmin --password-file {{ password_file }}
    - ssoadm_bin: "{{ tools_dir }}/{{ deployment_uri }}/bin/ssoadm"
    # - ssoadm_bin: "{{ tools_dir }}/{{ deployment_uri }}/bin/ssoadm {{ admin_creds }}"

  tasks:

    - name: create the password file
      shell: echo {{ admin_password }} > {{ password_file }}
             creates={{ password_file }}

    - name: set the permissions for the password file
      file: path={{ password_file }} mode=0400

    - name: verify this openam server
      # command: "{{ ssoadm_bin }} list-servers"
      command: "{{ ssoadm_bin }} list-servers {{ admin_creds }}"

    # NOTE: you can refer to the "default" server as well as individual ones
    # - name: enable debugging by default
      # command: {{ ssoadm_bin }} update-server-cfg --servername $server_name --attributevalues "com.iplanet.services.debug.level=message"

    # - name: list server config
      # command: {{ ssoadm_bin }} list-server-cfg --servername $server_name --withdefaults
      # command: {{ ssoadm_bin }} list-server-cfg --servername $server_name

    # - name: clean up the password file for security reasons
      # file: path={{ password_file }} state=absent
