# -*- mode: ruby -*-
# vi: set ft=ruby :

# require "vagrant-ansible"

Vagrant::Config.run do |config|

  # default vm configuration
  config.vm.box = "base"
  # config.vm.customize ["modifyvm", :id, "--memory", "512"]
  # config.vm.customize ["modifyvm", :id, "--cpus", "1"]

  config.vm.define :oig1 do |v|
    v.vm.network :hostonly, "10.0.0.2"
    v.vm.host_name = "oig1.example.com"

    # v.vm.provision :ansible do |ansible|
    #   # add this to the hosts that ansible manages
    #   ansible.hosts = v.vm.host_name

    #   ansible.playbook = "../../playbooks/setup.yml"

    #   ansible.sudo = "yes"

    #   # pass in required and optional build variables
    #   # some variables you might want to override:
    #   # - <product>_version
    #   # - logstash_memory
    #   ansible.extra_vars = {
    #     hosts: v.vm.host_name,
    #   }

    #   # enable verbose output
    #   ansible.options = "-vv"
    # end
  end
end
