# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws|
    aws.access_key_id = ENV["AWS_ACCESS_KEY"]
    aws.secret_access_key = ENV["AWS_SECRET_KEY"]
    aws.ssh_private_key_path = "$HOME/.ssh/fpg_rockie_rsa.pem"
    aws.instance_type = "t1.micro"
    aws.security_groups = [ "products" ]
    aws.region = "ap-southeast-2"
    aws.tags = {
      Name: "oig1.example.com"
    }

    aws.region_config "ap-southeast-2" do |region|
      region.ami = "ami-b6df4e8c"
      region.ssh_username = "ec2-user"
      region.keypair_name = "fpg_rockie"
      region.availability_zone = "ap-southeast-2a"
    end
  end
end
