# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "base"
  config.vm.box = "precise64"
  # config.vm.box = "centos_64"
  # config.vm.box = "dummy"
  # config.vm.network :private_network, ip: "10.0.0.10"

  config.vm.define :oig1 do |oig1|
    # common settings across providers
    hostname = "oig1.example.com"
    description = "openig with password replay"

    oig1.vm.provider(:vmware_fusion) do |f, override|
      # oig1.vm.box = "precise64"
      # override.config.vm.box = "precise64"
      override.vm.network :private_network, ip: "10.0.0.10"

      f.vmx["memsize"] = "512"
      f.vmx["numvcpus"] = "1"
      f.vmx["displayName"] = hostname
      f.vmx["annotation"] = description
    end

    oig1.vm.provider :aws do |aws, override|
      # override.vm.box = "dummy"

      aws.region = "ap-southeast-2"
      aws.instance_type = "t1.micro"
      aws.tags = {
        Name: hostname,
        description: description
      }

      aws.region_config "ap-southeast-2" do |region|
        region.availability_zone = "ap-southeast-2a"
        region.ami = "ami-b6df4e8c"
        region.keypair_name = "fpg_rockie"
        region.security_groups = [ "products" ]
      end

      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = ENV["HOME"] + "/.ssh/fpg_rockie_rsa.pem"
    end

    oig1.vm.provision :ansible do |ansible|
      # add this to the hosts that ansible manages
      ansible.inventory_file = "../../ansible/vagrant_hosts"

      ansible.playbook = "../../ansible/playbooks/setup.yml"

      ansible.sudo = true

      # pass in required and optional build variables
      # some variables you might want to override:
      # - <product>_version
      # - logstash_memory
      ansible.extra_vars = {
        # hosts: oig1.vm.host_name,
        # hosts: "v_" + hostname,
        hosts: "10.0.0.10"
      }

      ansible.verbose = true
    end
  end
end
