---

# assumptions: red hat based system. default system java. non production.

- name: set up logstash prerequisites on the system
  hosts: $hosts
  gather_facts: no

  vars_files:
    - ../vars/logstash.yml

  vars:
    - firewall_service: iptables

  tasks:

    - name: create artefact dir
      file: path=$artefact_dir
            state=directory

    - name: install java for logstash and graylog2 server
      yum: name=@java-platform
           state=present

    - name: install tar
      yum: name=tar
           state=present

    - name: install unzip
      yum: name=unzip
           state=present

    # - name: install node.js for statsd
    #   yum: name=node
        #   state=present

    # # TODO: make the repo a var
    # - name: clone the statsd project
    #   git: repo=https://github.com/etsy/statsd.git dest=/opt/statsd
    #   tags: quick

    # - name: install mongodb for graylog2 server
    #   yum: name=$item state=present
    #   with_items:
    #     - mongodb
    #     - mongodb-server
    #   when_set: $graylog2

    # - name: install requirements for graylog2 web
    #   yum: name="Development Tools" state=present
    #   yum: name=@dev state=present
    #   TODO: verify the short name for 'Development Tools'

    # - name: install requirements for graylog2 web
    #   yum: name=$item state=present
    #   with_items:
    #     - ruby
    #     - rubygems
    #     - rake
    #     - ruby-devel
    #     - openssl-devel
    #     - git

    - name: install bundler gem for kibana and graylog2 web
      gem: name=bundler
           state=present

    # - name: check if the epel repo is installed
    #   command: rpm -q epel-release
    #   register: epel_package
    #   ignore_errors: yes

    # # FIXME
    # - name: show if epel repo is installed
    #   debug: msg="epel_package = $epel_package"

    # # FIXME
    # http://ansible.cc/docs/playbooks2.html#register-variables
    # - name: install the epel repository (not needed by fedora)
    #   command: rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    #   # when_string: $ansible_distribution != "Fedora" and $ansible_kernel != "3.2.30-49.59.amzn1.x86_64"
    #   # TODO: look at ec2_facts to see if it can help figure uout if this is an ec2 instance, or maybe there's another way
    #   # when_string: $ansible_distribution != "Fedora" and "'is not installed' in $epel_package.stdout"
    #   ignore_errors: yes

    # # FIXME
    # http://ansible.cc/docs/playbooks2.html#register-variables
    # - name: install ansible fireball node
    #   yum: name=ansible-node-fireball
    #        state=present
    #   # when_string: $ansible_distribution == "Fedora" or "'is not installed' not in $epel_package"
    #   # when_string: $ansible_distribution == "Fedora" or "'is not installed' not in $epel_package"
    #   ignore_errors: yes

    # # FIXME
    # http://ansible.cc/docs/playbooks2.html#register-variables
    # - name: start a fireball connection
    #   action: fireball
    #   # when_string: "'is not installed' not in $epel_package"
    #   ignore_errors: yes
    #   tags: fireball

    - name: disable firewall now and after reboots
      service: name=$firewall_service
               state=stopped
               enabled=no
      when_unset: $production
