---

# TODO: make encryption_key optional, and required if $join_site is set or $lb_name is set. remove from vagrant and test. make a note that this should be set from the beginning (ie for server1) if a clustered configuration is desired.
# TODO: consider renaming join_site to join_site, to match openam terminology
# TODO: test initialise.yml
# TODO: test taking down a (theoretically) unhealthy server and rebuilding it and adding it to the cluster. for maximum effect, this should be the first server in the node. and make changes after bringing it down to see if it will replicate when you bring it back up.
# TODO: test with a third server (will need to reboot for that). this could have a console attached, as opposed to the first 2 in a user facing cluster.
# TODO: review these:
# http://wiki.opencsi.com/public/bin/view/OpenAM/SilentInstallation
# http://blog.profiq.cz/2012/01/19/automated-installation-and-configuration-of-openam/
# https://github.com/ConductAS/puppet-openam
# https://github.com/dgardnersf/puppet-openam

# assumptions: openam 11.0.0. embedded opendj config store. no user stores or
# further config. staging. red hat based systems. tomcat6. 1,024mb jvm.
#
# a default initialise playbook exists for some basic settings, mainly around
# verification, load balancing, and debugging. any further config or
# customisation (eg. custom auth modules, custom login pages, etc.) should go
# in specific playbooks for your own setup (ie. one or more configuration.yml
# files).
#
# the following build vars are optional (and disabled by default):
#
# - install_headless (any value to enable)
# - install_tools (any value to enable)
# - install_diagnostics (any value to enable)
# - join_site (any value to enable)
#     - existing_server_hostname (when join_site is enabled -- TODO: enforce)
#     - existing_server_id (when join_site is enabled -- TODO: enforce)
# - encryption_key (when join_site or lb_name are enabled -- TODO: enforce)
# - openam_java_opts (defaults to -Xmx1024m -XX:MaxPermSize=256m)
# - lb_site_name (for site/cluster configurations)
# - lb_primary_url (for site/cluster configurations)
# - container_ssl (any value to enable)
#     - container_storepass (when container_ssl is enabled -- TODO: enforce)
#     - container_keypass (when container_ssl is enabled -- TODO: enforce)

- name: set up openam
  hosts: $hosts
  gather_facts: no

  tasks:

    - name: fail if required build vars are unset
      fail: msg="please set all required build variables"
      with_items:
        - "{{ hostname }}"
        - "{{ cookie_domain }}"
        - "{{ deployment_uri }}"
        - "{{ root_suffix }}"
        - "{{ admin_password }}"
        - "{{ policy_agent_password }}"
        - "{{ config_store_password }}"
      # when: item is not defined
      # when: not item
      # when: item == None
      # FIXME: this is a hack, i would expect 'is not defined' to work
      when: item.startswith("{{")

- include: roles/common/tasks/system.yml
- include: roles/common/tasks/install.yml
# - include: roles/common/tasks/initialise.yml
# - include: roles/common/tasks/upgrade.yml
# - include: roles/common/tasks/uninstall.yml
