---

# TODO: find an init script (there's one for centos)

- hosts: $hosts
  gather_facts: no

  vars_files:
    - ../vars/logstash.yml

  vars:
    elasticsearch_version: 0.20.0
    elasticsearch_dir: $install_dir/elasticsearch
    elasticsearch_archive: http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$elasticsearch_version.zip

  tasks:

    - name: download elasticsearch
      get_url: url=$elasticsearch_archive dest=$artefact_dir

    - name: unzip elasticsearch archive
      command: unzip -qo $artefact_dir/elasticsearch-$elasticsearch_version.zip -d /opt

    - name: fix elasticsearch permissions
      command: chmod -R go-w /opt/elasticsearch-$elasticsearch_version

    - name: create a symbolic link
      file: src=/opt/elasticsearch-$elasticsearch_version
            dest=$elasticsearch_dir
            state=link

    - name: start elasticsearch
      command: $elasticsearch_dir/bin/elasticsearch
