---

# TODO: fix the init service (has no name)

- hosts: $hosts
  gather_facts: no

  vars_files:
    - ../vars/logstash.yml

  vars:
    - logstash_version: 1.1.9
    - logstash_dir: $install_dir/logstash
    # - logstash_jar: logstash-$logstash_version-flatjar.jar
    - logstash_jar: logstash-$logstash_version-monolithic.jar
    - logstash_archive: http://logstash.objects.dreamhost.com/release/$logstash_jar
    - logstash_memory: 128M
    - logstash_bin_dir: $logstash_dir/bin
    - logstash_conf_dir: $logstash_dir/conf
    - logstash_log_dir: $logstash_dir/log
    - logstash_patterns_dir: $logstash_dir/patterns

  tasks:

    - name: create main dir
      file: path=$logstash_dir
            state=directory

    - name: create bin dir
      file: path=$logstash_bin_dir
            state=directory

    - name: create conf dir
      file: path=$logstash_conf_dir
            state=directory

    - name: create log dir
      file: path=$logstash_log_dir
            state=directory

    - name: create patterns dir
      file: path=$logstash_patterns_dir
            state=directory

    - name: try to transfer jar first
      copy: src=../files/$logstash_jar
            dest=$artefact_dir
      register: transfer_result
      ignore_errors: yes

    - name: otherwise, download jar
      get_url: url=$logstash_archive dest=$artefact_dir
      when_failed: $transfer_result

    - name: copy jar to bin dir
      command: cp $artefact_dir/$logstash_jar $logstash_bin_dir

    - name: create a symbolic link
      file: src=$logstash_bin_dir/$logstash_jar
            dest=$logstash_bin_dir/logstash.jar
            state=link

    - name: transfer the init script
      template: src=../templates/logstash.sh
                dest=/etc/rc.d/init.d/logstash
                mode=0755

    - name: transfer a basic conf file
      template: src=../templates/logstash.conf
                dest=$logstash_conf_dir
                mode=0755

    - name: enable and start the service
      service: name=logstash
               enabled=yes
               state=started
